/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1967 from "./ERC1967";
export type { erc1967 };
export type { Proxy } from "./Proxy";
export type { ProxyAdmin } from "./ProxyAdmin";
export type { TransparentUpgradeableProxy } from "./TransparentUpgradeableProxy";
