/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IERCHandlerInterface extends ethers.utils.Interface {
  functions: {
    "setBurnable(address)": FunctionFragment;
    "setResource(bytes32,address)": FunctionFragment;
    "withdraw(bytes)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "setBurnable", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setResource",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "setBurnable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setResource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {};
}

export class IERCHandler extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IERCHandlerInterface;

  functions: {
    setBurnable(
      contractAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setBurnable(address)"(
      contractAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setResource(
      resourceID: BytesLike,
      contractAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setResource(bytes32,address)"(
      resourceID: BytesLike,
      contractAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdraw(
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdraw(bytes)"(
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  setBurnable(
    contractAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setBurnable(address)"(
    contractAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setResource(
    resourceID: BytesLike,
    contractAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setResource(bytes32,address)"(
    resourceID: BytesLike,
    contractAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdraw(
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdraw(bytes)"(
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    setBurnable(
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setBurnable(address)"(
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setResource(
      resourceID: BytesLike,
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setResource(bytes32,address)"(
      resourceID: BytesLike,
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(data: BytesLike, overrides?: CallOverrides): Promise<void>;

    "withdraw(bytes)"(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    setBurnable(
      contractAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setBurnable(address)"(
      contractAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setResource(
      resourceID: BytesLike,
      contractAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setResource(bytes32,address)"(
      resourceID: BytesLike,
      contractAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdraw(data: BytesLike, overrides?: Overrides): Promise<BigNumber>;

    "withdraw(bytes)"(
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setBurnable(
      contractAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setBurnable(address)"(
      contractAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setResource(
      resourceID: BytesLike,
      contractAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setResource(bytes32,address)"(
      resourceID: BytesLike,
      contractAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdraw(bytes)"(
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
