/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface NoArgumentInterface extends ethers.utils.Interface {
  functions: {
    "noArgument()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "noArgument",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "noArgument", data: BytesLike): Result;

  events: {
    "NoArgumentCalled()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NoArgumentCalled"): EventFragment;
}

export class NoArgument extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: NoArgumentInterface;

  functions: {
    noArgument(overrides?: Overrides): Promise<ContractTransaction>;

    "noArgument()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  noArgument(overrides?: Overrides): Promise<ContractTransaction>;

  "noArgument()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    noArgument(overrides?: CallOverrides): Promise<void>;

    "noArgument()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    NoArgumentCalled(): EventFilter;
  };

  estimateGas: {
    noArgument(overrides?: Overrides): Promise<BigNumber>;

    "noArgument()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    noArgument(overrides?: Overrides): Promise<PopulatedTransaction>;

    "noArgument()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
